/**
 * Schema DDL for both backends.
 *
 * The SQLite column types are kept exactly as they shipped so an existing
 * cachet.db file is still valid -- `CREATE TABLE IF NOT EXISTS` is a no-op
 * against it. The Postgres types differ where SQLite's dynamic typing was doing
 * the work for us:
 *
 *   - epoch-millisecond columns are BIGINT (they overflow a 32-bit INTEGER)
 *   - `total_response_time` is DOUBLE PRECISION, because response times come
 *     from `performance.now()` and are fractional; a Postgres INTEGER column
 *     would round every one of them
 *
 * camelCase columns are double-quoted so Postgres preserves their case instead
 * of folding to lowercase. SQLite accepts the same quoting.
 */

import type { Dialect } from "./types";

/** Longest value stored in a column that participates in a primary key. */
export const MAX_KEY_TEXT_LENGTH = 512;

export function schemaStatements(dialect: Dialect): string[] {
	const sqlite = dialect === "sqlite";

	// SQLite stores these as clustered key-only b-trees; Postgres has no
	// equivalent and simply ignores the concept.
	const withoutRowId = sqlite ? " WITHOUT ROWID" : "";
	// Epoch milliseconds. SQLite's INTEGER is already 64-bit.
	const epochMs = sqlite ? "INTEGER" : "BIGINT";
	const autoId = sqlite
		? "INTEGER PRIMARY KEY AUTOINCREMENT"
		: "BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY";
	const responseTime = sqlite ? "INTEGER" : "DOUBLE PRECISION";

	return [
		`CREATE TABLE IF NOT EXISTS users (
			id TEXT PRIMARY KEY,
			"userId" TEXT UNIQUE,
			"displayName" TEXT,
			"realName" TEXT,
			pronouns TEXT,
			"imageUrl" TEXT,
			expiration ${epochMs}
		)`,

		`CREATE TABLE IF NOT EXISTS emojis (
			id TEXT PRIMARY KEY,
			name TEXT UNIQUE,
			alias TEXT,
			"imageUrl" TEXT,
			expiration ${epochMs}
		)`,

		...["traffic_10min", "traffic_hourly", "traffic_daily"].map(
			(table) => `CREATE TABLE IF NOT EXISTS ${table} (
			bucket ${epochMs} NOT NULL,
			endpoint TEXT NOT NULL,
			status_code INTEGER NOT NULL,
			hits INTEGER NOT NULL DEFAULT 1,
			total_response_time ${responseTime} NOT NULL DEFAULT 0,
			PRIMARY KEY (bucket, endpoint, status_code)
		)${withoutRowId}`,
		),

		`CREATE TABLE IF NOT EXISTS user_agent_stats (
			user_agent TEXT PRIMARY KEY,
			hits INTEGER NOT NULL DEFAULT 1,
			last_seen ${epochMs} NOT NULL
		)${withoutRowId}`,

		`CREATE TABLE IF NOT EXISTS referer_stats (
			referer_host TEXT PRIMARY KEY,
			hits INTEGER NOT NULL DEFAULT 1,
			last_seen ${epochMs} NOT NULL
		)${withoutRowId}`,

		`CREATE TABLE IF NOT EXISTS uptime_sessions (
			id ${autoId},
			start_time ${epochMs} NOT NULL,
			end_time ${epochMs},
			duration ${epochMs}
		)`,

		"CREATE INDEX IF NOT EXISTS idx_traffic_10min_bucket ON traffic_10min(bucket)",
		"CREATE INDEX IF NOT EXISTS idx_traffic_hourly_bucket ON traffic_hourly(bucket)",
		"CREATE INDEX IF NOT EXISTS idx_traffic_daily_bucket ON traffic_daily(bucket)",
		"CREATE INDEX IF NOT EXISTS idx_user_agent_hits ON user_agent_stats(hits DESC)",
		"CREATE INDEX IF NOT EXISTS idx_referer_hits ON referer_stats(hits DESC)",
	];
}

/**
 * DDL that only applies to databases created by an older version.
 *
 * Postgres never needs these: its schema is only ever created by the statements
 * above, which already include every column.
 */
export function legacyColumnPatches(dialect: Dialect): string[] {
	if (dialect !== "sqlite") return [];
	return [`ALTER TABLE users ADD COLUMN "realName" TEXT`];
}
