import { version } from "../../package.json";
import { asNumber } from "../db/dialect";
import type { Db, Queryable } from "../db/types";
import type { Migration } from "./types";

/**
 * Migration Manager for handling database schema and data migrations
 */
export class MigrationManager {
	private db: Db;
	private currentVersion: string;
	private migrations: Migration[];

	constructor(db: Db, migrations: Migration[]) {
		this.db = db;
		this.currentVersion = version;
		// Migrations that target a different backend can never apply here.
		this.migrations = migrations.filter(
			(migration) =>
				!migration.dialects || migration.dialects.includes(db.dialect),
		);
	}

	private async initMigrationTable() {
		const autoId =
			this.db.dialect === "sqlite"
				? "INTEGER PRIMARY KEY AUTOINCREMENT"
				: "BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY";
		const epochMs = this.db.dialect === "sqlite" ? "INTEGER" : "BIGINT";

		await this.db.run(`
      CREATE TABLE IF NOT EXISTS migrations (
        id ${autoId},
        version TEXT NOT NULL,
        applied_at ${epochMs} NOT NULL,
        description TEXT
      )
    `);
	}

	private async getLastAppliedMigration(): Promise<{
		version: string;
		applied_at: number;
	} | null> {
		return this.db.get<{ version: string; applied_at: number }>(`
      SELECT version, ${asNumber("applied_at")} AS applied_at FROM migrations
      ORDER BY applied_at DESC LIMIT 1
    `);
	}

	private async isMigrationApplied(version: string): Promise<boolean> {
		const result = await this.db.get<{ count: number }>(
			`
      SELECT ${asNumber("COUNT(*)")} as count FROM migrations
      WHERE version = ?
    `,
			[version],
		);

		return (result?.count ?? 0) > 0;
	}

	private async recordMigration(
		db: Queryable,
		version: string,
		description: string,
	) {
		await db.run(
			`
      INSERT INTO migrations (version, applied_at, description)
      VALUES (?, ?, ?)
    `,
			[version, Date.now(), description],
		);
	}

	async runMigrations(): Promise<{
		success: boolean;
		migrationsApplied: number;
		lastAppliedVersion: string | null;
		error?: string;
	}> {
		try {
			await this.initMigrationTable();

			const sortedMigrations = [...this.migrations].sort((a, b) => {
				return this.compareVersions(a.version, b.version);
			});

			const lastApplied = await this.getLastAppliedMigration();
			let migrationsApplied = 0;
			let lastAppliedVersion = lastApplied?.version || null;

			console.log(`Current app version: ${this.currentVersion}`);
			console.log(`Last applied migration: ${lastAppliedVersion || "None"}`);

			if (!lastAppliedVersion) {
				const previousVersion = this.getPreviousVersion(this.currentVersion);
				if (previousVersion) {
					console.log(
						`No migrations table found. Assuming upgrade from ${previousVersion}`,
					);
					await this.recordMigration(
						this.db,
						previousVersion,
						"Virtual migration for existing installation",
					);
					lastAppliedVersion = previousVersion;
				}
			}

			for (const migration of sortedMigrations) {
				if (await this.isMigrationApplied(migration.version)) {
					console.log(
						`Migration ${migration.version} already applied, skipping`,
					);
					continue;
				}

				if (this.compareVersions(migration.version, this.currentVersion) > 0) {
					console.log(
						`Migration ${migration.version} is for a future version, skipping`,
					);
					continue;
				}

				if (
					lastAppliedVersion &&
					this.compareVersions(migration.version, lastAppliedVersion) <= 0
				) {
					console.log(
						`Migration ${migration.version} is older than last applied (${lastAppliedVersion}), skipping`,
					);
					continue;
				}

				console.log(
					`Applying migration ${migration.version}: ${migration.description}`,
				);

				try {
					await this.db.transaction(async (tx) => {
						await migration.up(tx);
						await this.recordMigration(
							tx,
							migration.version,
							migration.description,
						);
					});
				} catch (migrationError) {
					throw new Error(
						`Migration ${migration.version} failed: ${migrationError instanceof Error ? migrationError.message : String(migrationError)}`,
					);
				}

				migrationsApplied++;
				lastAppliedVersion = migration.version;
				console.log(`Migration ${migration.version} applied successfully`);
			}

			return {
				success: true,
				migrationsApplied,
				lastAppliedVersion,
			};
		} catch (error) {
			console.error("Error running migrations:", error);
			return {
				success: false,
				migrationsApplied: 0,
				lastAppliedVersion: null,
				error: error instanceof Error ? error.message : String(error),
			};
		}
	}

	private getPreviousVersion(version: string): string | null {
		const parts = version.split(".");
		if (parts.length !== 3) return null;

		const [major, minor, patch] = parts.map(Number);
		if (major === undefined || minor === undefined || patch === undefined) {
			return null;
		}

		if (patch > 0) {
			return `${major}.${minor}.${patch - 1}`;
		}
		if (minor > 0) {
			return `${major}.${minor - 1}.0`;
		}
		if (major > 0) {
			return `${major - 1}.0.0`;
		}

		return null;
	}

	private compareVersions(a: string, b: string): number {
		const partsA = a.split(".").map(Number);
		const partsB = b.split(".").map(Number);

		for (let i = 0; i < Math.max(partsA.length, partsB.length); i++) {
			const partA = partsA[i] ?? 0;
			const partB = partsB[i] ?? 0;

			if (partA < partB) return -1;
			if (partA > partB) return 1;
		}

		return 0;
	}
}
