on:
  push:
    branches:
      - main
  workflow_dispatch:
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Setup Tailscale
        uses: tailscale/github-action@v3
        with:
          oauth-client-id: ${{ secrets.TS_OAUTH_CLIENT_ID }}
          oauth-secret: ${{ secrets.TS_OAUTH_SECRET }}
          tags: tag:ci
          use-cache: "true"
      - name: Configure SSH
        run: |
          mkdir -p ~/.ssh
          echo "StrictHostKeyChecking no" >> ~/.ssh/config
      - name: file commands
        run: |
          ssh kierank@ember << 'EOF'
            cd ~/cachet
            git fetch --all
            git reset --hard origin/main
            ~/.bun/bin/bun install
            rm data/cachet.db
            sudo /usr/bin/systemctl restart cachet.service
          EOF
